services:
  - mongodb

environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn lint
  - yarn test
  - yarn build

# Don't actually build.
build: off
