services:
  - mongodb

environment:
  nodejs_version: "12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test
  - npm run build

# Don't actually build.
build: off
