blog:
  build: .
  ports:
    - "3000:3000"
  environment:
    - MONGO_HOST=mongo-master
    - MONGO_PORT=27017
    - MONGO_DATABASE=blog
  links:
    - mongo-master
  hostname: blogserver
  restart: always

mongo-master:
  hostname: mongoserver
  image: mongo:3.6
  volumes:
    - ./mongo-data:/data/db
  restart: always
